### ISSUE TITLE
Please correct bold mode in pc-tty

### ISSUE THREAD

**Issue by pawelpisarczyk** [phoenix-rtos/phoenix-rtos-devices#50]
![image](https://user-images.githubusercontent.com/37936870/89197471-0d276c00-d5ac-11ea-8f26-aeab3d214012.png)

**Comment by Maxez** [comment]
Fixed by [0829e20](https://github.com/phoenix-rtos/phoenix-rtos-devices/commit/0829e208b94bcd122a5fdaaadc3c4f9221e42a0f).
To be clear, the bold mode is defined as white text on black background (as far as I know VGA doesn't have default bold fonts, we would have to load one manually).
