### ISSUE TITLE
imx6ull-flash: Adding support for NOR flash available on reference board.

### ISSUE THREAD

**Issue by pawelpisarczyk** [phoenix-rtos/phoenix-rtos-devices#57]
Currently, imx6ull-flash driver support only NAND flash used in DCU project. The support of NOR flash available on iMX 6ULL reference board should be implemented.

**Comment by agkaminski** [comment]
Solved in https://github.com/phoenix-rtos/phoenix-rtos-devices/commit/8ecf9a858df97044f2bcd333acda6e4b7242666b
